# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import meter_pb2 as protos_dot_meter__pb2


class MeterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReadMeter = channel.unary_stream(
                '/meter.Meter/ReadMeter',
                request_serializer=protos_dot_meter__pb2.MeterRequest.SerializeToString,
                response_deserializer=protos_dot_meter__pb2.MeterReading.FromString,
                )


class MeterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReadMeter(self, request, context):
        """return RPC streaming meter data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MeterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReadMeter': grpc.unary_stream_rpc_method_handler(
                    servicer.ReadMeter,
                    request_deserializer=protos_dot_meter__pb2.MeterRequest.FromString,
                    response_serializer=protos_dot_meter__pb2.MeterReading.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'meter.Meter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Meter(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReadMeter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/meter.Meter/ReadMeter',
            protos_dot_meter__pb2.MeterRequest.SerializeToString,
            protos_dot_meter__pb2.MeterReading.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
